captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
email:
  to: 835106505@qq.com
  port: 465
  from: 18260.56308@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
jwt:
  signing-key: qmPlus
  expires-time: 604800
  buffer-time: 86400
local:
  path: uploads/file
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ginvueadmin
  username: root
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""
qiniu:
  zone: ZoneHuadong
  bucket: qm-plus-img
  img-path: http://qmplusimg.henrongyi.top
  use-https: false
  access-key: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
zap:
  level: debug
  format: console
  prefix: '[ONLINE-DOC]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
